# Generated by Django 5.0.7 on 2024-07-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liriodosvales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=10),
        ),
    ]
