# Generated by Django 5.0.7 on 2024-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liriodosvales', '0002_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacao',
            name='posologia',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicacao',
            name='dosagem',
            field=models.CharField(max_length=100),
        ),
    ]
