# Generated by Django 5.0.7 on 2024-07-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liriodosvales', '0002_atendimentomedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentomedico',
            name='tipo_atendimento',
        ),
    ]
