# Generated by Django 5.0.7 on 2024-07-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liriodosvales', '0003_remove_atendimentomedico_tipo_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentomedico',
            name='hipotese_diagnostica',
        ),
        migrations.AddField(
            model_name='atendimentomedico',
            name='hipotese_diagnostica_cid',
            field=models.CharField(default='Z000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atendimentomedico',
            name='hipotese_diagnostica_nome',
            field=models.CharField(default='Z000', max_length=255),
            preserve_default=False,
        ),
    ]
