# Generated by Django 5.0.7 on 2024-07-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liriodosvales', '0005_atendimentomedico_historia_doenca_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacao',
            name='atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liriodosvales.atendimentomedico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicacao',
            name='dosagem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicacao',
            name='posologia',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liriodosvales.atendimentomedico')),
            ],
        ),
        migrations.CreateModel(
            name='ExameComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liriodosvales.atendimentomedico')),
            ],
        ),
    ]
